<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/apponly.proto

namespace GPBMetadata\Meshtastic;

class Apponly
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Meshtastic\Channel::initOnce();
        \GPBMetadata\Meshtastic\Config::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c020a186d6573687461737469632f6170706f6e6c792e70726f746f120a6d6573687461737469631a176d6573687461737469632f636f6e6669672e70726f746f226f0a0a4368616e6e656c536574122d0a0873657474696e677318012003280b321b2e6d6573687461737469632e4368616e6e656c53657474696e677312320a0b6c6f72615f636f6e66696718022001280b321d2e6d6573687461737469632e436f6e6669672e4c6f5261436f6e66696742620a13636f6d2e6765656b7376696c6c652e6d657368420d4170704f6e6c7950726f746f735a226769746875622e636f6d2f6d6573687461737469632f676f2f67656e657261746564aa02144d6573687461737469632e50726f746f62756673ba0200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

