<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/cannedmessages.proto

namespace GPBMetadata\Meshtastic;

class Cannedmessages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad4010a1f6d6573687461737469632f63616e6e65646d657373616765732e70726f746f120a6d657368746173746963222d0a1943616e6e65644d6573736167654d6f64756c65436f6e66696712100a086d65737361676573180120012809426e0a13636f6d2e6765656b7376696c6c652e6d657368421943616e6e65644d657373616765436f6e66696750726f746f735a226769746875622e636f6d2f6d6573687461737469632f676f2f67656e657261746564aa02144d6573687461737469632e50726f746f62756673ba0200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

