<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mqtt.proto

namespace GPBMetadata\Meshtastic;

class Mqtt
{
    public static $is_initialized = false;

    public static function initOnce() {
        if (self::$is_initialized) {
            return;
        }
        self::$is_initialized = true;
    }
}
