<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/paxcount.proto

namespace GPBMetadata\Meshtastic;

class Paxcount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb010a196d6573687461737469632f706178636f756e742e70726f746f120a6d65736874617374696322350a08506178636f756e74120c0a047769666918012001280d120b0a03626c6518022001280d120e0a06757074696d6518032001280d42630a13636f6d2e6765656b7376696c6c652e6d657368420e506178636f756e7450726f746f735a226769746875622e636f6d2f6d6573687461737469632f676f2f67656e657261746564aa02144d6573687461737469632e50726f746f62756673ba0200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

