<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/rtttl.proto

namespace GPBMetadata\Meshtastic;

class Rtttl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a166d6573687461737469632f727474746c2e70726f746f120a6d657368746173746963221f0a0b525454544c436f6e66696712100a0872696e67746f6e6518012001280942660a13636f6d2e6765656b7376696c6c652e6d6573684211525454544c436f6e66696750726f746f735a226769746875622e636f6d2f6d6573687461737469632f676f2f67656e657261746564aa02144d6573687461737469632e50726f746f62756673ba0200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

