<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

/**
 * Simple Data implementation for parsing MQTT messages
 */
class Data
{
    private $portnum = 0;
    private $payload = '';
    private $want_response = false;
    private $dest = 0;
    private $source = 0;
    private $request_id = 0;

    public function __construct($data = NULL) {
        // Simple constructor
    }

    public function mergeFromString(string $data): void
    {
        $this->parseFields($data);
    }

    private function parseFields(string $data): void
    {
        $pos = 0;
        $len = strlen($data);
        
        while ($pos < $len) {
            if ($pos >= $len) break;
            
            $tag = ord($data[$pos]) >> 3;
            $wire_type = ord($data[$pos]) & 0x07;
            $pos++;
            
            switch ($tag) {
                case 1: // portnum
                    if ($wire_type == 0) { // varint
                        $this->portnum = $this->readVarint($data, $pos);
                    }
                    break;
                case 2: // payload
                    if ($wire_type == 2) { // length-delimited
                        $length = $this->readVarint($data, $pos);
                        $this->payload = substr($data, $pos, $length);
                        $pos += $length;
                    }
                    break;
                case 3: // want_response
                    if ($wire_type == 0) { // varint
                        $this->want_response = $this->readVarint($data, $pos) !== 0;
                    }
                    break;
                case 4: // dest
                    if ($wire_type == 0) { // varint
                        $this->dest = $this->readVarint($data, $pos);
                    }
                    break;
                case 5: // source
                    if ($wire_type == 0) { // varint
                        $this->source = $this->readVarint($data, $pos);
                    }
                    break;
                case 6: // request_id
                    if ($wire_type == 0) { // varint
                        $this->request_id = $this->readVarint($data, $pos);
                    }
                    break;
                default:
                    // Skip unknown fields
                    $pos = $this->skipField($data, $pos, $wire_type);
                    break;
            }
        }
    }

    private function readVarint(string $data, int &$pos): int
    {
        $result = 0;
        $shift = 0;
        while ($pos < strlen($data)) {
            $byte = ord($data[$pos++]);
            $result |= ($byte & 0x7F) << $shift;
            if (($byte & 0x80) == 0) break;
            $shift += 7;
        }
        return $result;
    }

    private function skipField(string $data, int $pos, int $wire_type): int
    {
        switch ($wire_type) {
            case 0: // varint
                while ($pos < strlen($data) && (ord($data[$pos]) & 0x80)) $pos++;
                return $pos + 1;
            case 1: // 64-bit
                return $pos + 8;
            case 2: // length-delimited
                $length = $this->readVarint($data, $pos);
                return $pos + $length;
            case 5: // 32-bit
                return $pos + 4;
            default:
                return $pos;
        }
    }

    public function getPortnum(): int { return $this->portnum; }
    public function getPayload(): string { return $this->payload; }
    public function getWantResponse(): bool { return $this->want_response; }
    public function getDest(): int { return $this->dest; }
    public function getSource(): int { return $this->source; }
    public function getRequestId(): int { return $this->request_id; }
}
