<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.MapReport</code>
 */
class MapReport extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string long_name = 1;</code>
     */
    protected $long_name = '';
    /**
     * Generated from protobuf field <code>string short_name = 2;</code>
     */
    protected $short_name = '';
    /**
     * Generated from protobuf field <code>.meshtastic.HardwareModel role = 3;</code>
     */
    protected $role = 0;
    /**
     * Generated from protobuf field <code>string firmware_version = 4;</code>
     */
    protected $firmware_version = '';
    /**
     * Generated from protobuf field <code>.meshtastic.Config.LoRaConfig.RegionCode region = 5;</code>
     */
    protected $region = 0;
    /**
     * Generated from protobuf field <code>.meshtastic.Config.LoRaConfig.ModemPreset modem_preset = 6;</code>
     */
    protected $modem_preset = 0;
    /**
     * Generated from protobuf field <code>bool has_default_channel = 7;</code>
     */
    protected $has_default_channel = false;

    /**
     * Constructor.
     */
    public function __construct($data = NULL) {
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string long_name = 1;</code>
     */
    public function getLongName()
    {
        return $this->long_name;
    }

    /**
     * Generated from protobuf field <code>string long_name = 1;</code>
     */
    public function setLongName($var)
    {
        GPBUtil::checkString($var, True);
        $this->long_name = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>string short_name = 2;</code>
     */
    public function getShortName()
    {
        return $this->short_name;
    }

    /**
     * Generated from protobuf field <code>string short_name = 2;</code>
     */
    public function setShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->short_name = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.HardwareModel role = 3;</code>
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.HardwareModel role = 3;</code>
     */
    public function setRole($var)
    {
        GPBUtil::checkInt32($var);
        $this->role = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>string firmware_version = 4;</code>
     */
    public function getFirmwareVersion()
    {
        return $this->firmware_version;
    }

    /**
     * Generated from protobuf field <code>string firmware_version = 4;</code>
     */
    public function setFirmwareVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->firmware_version = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.Config.LoRaConfig.RegionCode region = 5;</code>
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.Config.LoRaConfig.RegionCode region = 5;</code>
     */
    public function setRegion($var)
    {
        GPBUtil::checkInt32($var);
        $this->region = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.Config.LoRaConfig.ModemPreset modem_preset = 6;</code>
     */
    public function getModemPreset()
    {
        return $this->modem_preset;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.Config.LoRaConfig.ModemPreset modem_preset = 6;</code>
     */
    public function setModemPreset($var)
    {
        GPBUtil::checkInt32($var);
        $this->modem_preset = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>bool has_default_channel = 7;</code>
     */
    public function getHasDefaultChannel()
    {
        return $this->has_default_channel;
    }

    /**
     * Generated from protobuf field <code>bool has_default_channel = 7;</code>
     */
    public function setHasDefaultChannel($var)
    {
        GPBUtil::checkBool($var);
        $this->has_default_channel = $var;
        return $this;
    }
}
