<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

/**
 * Simple MeshPacket implementation for parsing MQTT messages
 */
class MeshPacket
{
    private $from = 0;
    private $to = 0;
    private $id = 0;
    private $rx_time = 0;
    private $rx_snr = 0.0;
    private $rx_rssi = 0;
    private $decoded = null;
    private $encrypted = '';

    public function __construct($data = NULL) {
        // Simple constructor
    }

    public function mergeFromString(string $data): void
    {
        $this->parseFields($data);
    }

    private function parseFields(string $data): void
    {
        $pos = 0;
        $len = strlen($data);
        
        while ($pos < $len) {
            if ($pos >= $len) break;
            
            $tag = ord($data[$pos]) >> 3;
            $wire_type = ord($data[$pos]) & 0x07;
            $pos++;
            
            switch ($tag) {
                case 1: // from
                    if ($wire_type == 5) { // fixed32
                        $this->from = unpack('V', substr($data, $pos, 4))[1];
                        $pos += 4;
                    }
                    break;
                case 2: // to
                    if ($wire_type == 5) { // fixed32
                        $this->to = unpack('V', substr($data, $pos, 4))[1];
                        $pos += 4;
                    }
                    break;
                case 3: // decoded
                    if ($wire_type == 2) { // length-delimited
                        $length = $this->readVarint($data, $pos);
                        $decoded_data = substr($data, $pos, $length);
                        $this->decoded = new Data();
                        $this->decoded->mergeFromString($decoded_data);
                        $pos += $length;
                    }
                    break;
                case 4: // encrypted
                    if ($wire_type == 2) { // length-delimited
                        $length = $this->readVarint($data, $pos);
                        $this->encrypted = substr($data, $pos, $length);
                        $pos += $length;
                    }
                    break;
                case 6: // id
                    if ($wire_type == 0) { // varint
                        $this->id = $this->readVarint($data, $pos);
                    }
                    break;
                case 7: // rx_snr
                    if ($wire_type == 5) { // fixed32 (float)
                        $this->rx_snr = unpack('f', substr($data, $pos, 4))[1];
                        $pos += 4;
                    }
                    break;
                case 8: // rx_rssi
                    if ($wire_type == 0) { // varint
                        $this->rx_rssi = $this->readVarint($data, $pos);
                    }
                    break;
                case 9: // rx_time
                    if ($wire_type == 5) { // fixed32
                        $this->rx_time = unpack('V', substr($data, $pos, 4))[1];
                        $pos += 4;
                    }
                    break;
                default:
                    // Skip unknown fields
                    $pos = $this->skipField($data, $pos, $wire_type);
                    break;
            }
        }
    }

    private function readVarint(string $data, int &$pos): int
    {
        $result = 0;
        $shift = 0;
        while ($pos < strlen($data)) {
            $byte = ord($data[$pos++]);
            $result |= ($byte & 0x7F) << $shift;
            if (($byte & 0x80) == 0) break;
            $shift += 7;
        }
        return $result;
    }

    private function skipField(string $data, int $pos, int $wire_type): int
    {
        switch ($wire_type) {
            case 0: // varint
                while ($pos < strlen($data) && (ord($data[$pos]) & 0x80)) $pos++;
                return $pos + 1;
            case 1: // 64-bit
                return $pos + 8;
            case 2: // length-delimited
                $length = $this->readVarint($data, $pos);
                return $pos + $length;
            case 5: // 32-bit
                return $pos + 4;
            default:
                return $pos;
        }
    }

    public function getFrom(): int { return $this->from; }
    public function getTo(): int { return $this->to; }
    public function getId(): int { return $this->id; }
    public function getRxTime(): int { return $this->rx_time; }
    public function getRxSnr(): float { return $this->rx_snr; }
    public function getRxRssi(): int { return $this->rx_rssi; }
    public function hasRxSnr(): bool { return $this->rx_snr !== 0.0; }
    public function hasRxRssi(): bool { return $this->rx_rssi !== 0; }
    public function getDecoded(): ?Data { return $this->decoded; }
    public function hasDecoded(): bool { return $this->decoded !== null; }
    public function getEncrypted(): string { return $this->encrypted; }
    public function hasEncrypted(): bool { return $this->encrypted !== ''; }
}
