<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.NeighborInfo</code>
 */
class NeighborInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 node_id = 1;</code>
     */
    protected $node_id = 0;
    /**
     * Generated from protobuf field <code>uint32 last_sent_by_id = 2;</code>
     */
    protected $last_sent_by_id = 0;
    /**
     * Generated from protobuf field <code>uint32 node_broadcast_interval_secs = 3;</code>
     */
    protected $node_broadcast_interval_secs = 0;
    /**
     * Generated from protobuf field <code>repeated .meshtastic.Neighbor neighbors = 4;</code>
     */
    private $neighbors;

    /**
     * Constructor.
     */
    public function __construct($data = NULL) {
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 node_id = 1;</code>
     */
    public function getNodeId()
    {
        return $this->node_id;
    }

    /**
     * Generated from protobuf field <code>uint32 node_id = 1;</code>
     */
    public function setNodeId($var)
    {
        GPBUtil::checkUint32($var);
        $this->node_id = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 last_sent_by_id = 2;</code>
     */
    public function getLastSentById()
    {
        return $this->last_sent_by_id;
    }

    /**
     * Generated from protobuf field <code>uint32 last_sent_by_id = 2;</code>
     */
    public function setLastSentById($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_sent_by_id = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 node_broadcast_interval_secs = 3;</code>
     */
    public function getNodeBroadcastIntervalSecs()
    {
        return $this->node_broadcast_interval_secs;
    }

    /**
     * Generated from protobuf field <code>uint32 node_broadcast_interval_secs = 3;</code>
     */
    public function setNodeBroadcastIntervalSecs($var)
    {
        GPBUtil::checkUint32($var);
        $this->node_broadcast_interval_secs = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .meshtastic.Neighbor neighbors = 4;</code>
     */
    public function getNeighbors()
    {
        return $this->neighbors;
    }

    /**
     * Generated from protobuf field <code>repeated .meshtastic.Neighbor neighbors = 4;</code>
     */
    public function setNeighbors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE);
        $this->neighbors = $arr;
        return $this;
    }
}
