<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.Position</code>
 */
class Position extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>sfixed32 latitude_i = 1;</code>
     */
    protected $latitude_i = 0;
    /**
     * Generated from protobuf field <code>sfixed32 longitude_i = 2;</code>
     */
    protected $longitude_i = 0;
    /**
     * Generated from protobuf field <code>int32 altitude = 3;</code>
     */
    protected $altitude = 0;
    /**
     * Generated from protobuf field <code>uint32 time = 4;</code>
     */
    protected $time = 0;

    /**
     * Constructor.
     */
    public function __construct($data = NULL) {
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>sfixed32 latitude_i = 1;</code>
     */
    public function getLatitudeI()
    {
        return $this->latitude_i;
    }

    /**
     * Generated from protobuf field <code>sfixed32 latitude_i = 1;</code>
     */
    public function setLatitudeI($var)
    {
        GPBUtil::checkInt32($var);
        $this->latitude_i = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed32 longitude_i = 2;</code>
     */
    public function getLongitudeI()
    {
        return $this->longitude_i;
    }

    /**
     * Generated from protobuf field <code>sfixed32 longitude_i = 2;</code>
     */
    public function setLongitudeI($var)
    {
        GPBUtil::checkInt32($var);
        $this->longitude_i = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 altitude = 3;</code>
     */
    public function getAltitude()
    {
        return $this->altitude;
    }

    /**
     * Generated from protobuf field <code>int32 altitude = 3;</code>
     */
    public function setAltitude($var)
    {
        GPBUtil::checkInt32($var);
        $this->altitude = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 time = 4;</code>
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>uint32 time = 4;</code>
     */
    public function setTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->time = $var;
        return $this;
    }
}
