<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.RouteDiscovery</code>
 */
class RouteDiscovery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated fixed32 route = 1;</code>
     */
    private $route;

    /**
     * Constructor.
     */
    public function __construct($data = NULL) {
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 route = 1;</code>
     */
    public function getRoute()
    {
        return $this->route;
    }

    /**
     * Generated from protobuf field <code>repeated fixed32 route = 1;</code>
     */
    public function setRoute($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED32);
        $this->route = $arr;
        return $this;
    }
}
