<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mqtt.proto

namespace Meshtastic;

/**
 * Simple ServiceEnvelope implementation for parsing MQTT messages
 */
class ServiceEnvelope
{
    private $packet = null;
    private $channel_id = '';
    private $gateway_id = '';

    public function __construct($data = NULL) {
        // Simple constructor without protobuf metadata
    }

    public function mergeFromString(string $data): void
    {
        // Simple protobuf parsing - look for the envelope structure
        // This is a simplified parser that extracts the basic fields we need
        $this->parseFields($data);
    }

    private function parseFields(string $data): void
    {
        $pos = 0;
        $len = strlen($data);
        
        while ($pos < $len) {
            if ($pos >= $len) break;
            
            $tag = ord($data[$pos]) >> 3;
            $wire_type = ord($data[$pos]) & 0x07;
            $pos++;
            
            switch ($tag) {
                case 1: // packet field
                    if ($wire_type == 2) { // length-delimited
                        $length = $this->readVarint($data, $pos);
                        $packet_data = substr($data, $pos, $length);
                        $this->packet = new MeshPacket();
                        $this->packet->mergeFromString($packet_data);
                        $pos += $length;
                    }
                    break;
                case 2: // channel_id field
                    if ($wire_type == 2) { // length-delimited
                        $length = $this->readVarint($data, $pos);
                        $this->channel_id = substr($data, $pos, $length);
                        $pos += $length;
                    }
                    break;
                case 3: // gateway_id field
                    if ($wire_type == 2) { // length-delimited
                        $length = $this->readVarint($data, $pos);
                        $this->gateway_id = substr($data, $pos, $length);
                        $pos += $length;
                    }
                    break;
                default:
                    // Skip unknown fields
                    $pos = $this->skipField($data, $pos, $wire_type);
                    break;
            }
        }
    }

    private function readVarint(string $data, int &$pos): int
    {
        $result = 0;
        $shift = 0;
        while ($pos < strlen($data)) {
            $byte = ord($data[$pos++]);
            $result |= ($byte & 0x7F) << $shift;
            if (($byte & 0x80) == 0) break;
            $shift += 7;
        }
        return $result;
    }

    private function skipField(string $data, int $pos, int $wire_type): int
    {
        switch ($wire_type) {
            case 0: // varint
                while ($pos < strlen($data) && (ord($data[$pos]) & 0x80)) $pos++;
                return $pos + 1;
            case 1: // 64-bit
                return $pos + 8;
            case 2: // length-delimited
                $length = $this->readVarint($data, $pos);
                return $pos + $length;
            case 5: // 32-bit
                return $pos + 4;
            default:
                return $pos;
        }
    }

    public function getPacket(): ?MeshPacket
    {
        return $this->packet;
    }

    public function hasPacket(): bool
    {
        return $this->packet !== null;
    }

    public function getChannelId(): string
    {
        return $this->channel_id;
    }

    public function getGatewayId(): string
    {
        return $this->gateway_id;
    }
}
