<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/telemetry.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.Telemetry</code>
 */
class Telemetry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 time = 1;</code>
     */
    protected $time = 0;
    protected $variant;

    /**
     * Constructor.
     */
    public function __construct($data = NULL) {
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 time = 1;</code>
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>uint32 time = 1;</code>
     */
    public function setTime($var)
    {
        GPBUtil::checkUint32($var);
        $this->time = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.DeviceMetrics device_metrics = 2;</code>
     */
    public function getDeviceMetrics()
    {
        return $this->readOneof(2);
    }

    public function hasDeviceMetrics()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.meshtastic.DeviceMetrics device_metrics = 2;</code>
     */
    public function setDeviceMetrics($var)
    {
        $this->writeOneof(2, $var);
        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.EnvironmentMetrics environment_metrics = 3;</code>
     */
    public function getEnvironmentMetrics()
    {
        return $this->readOneof(3);
    }

    public function hasEnvironmentMetrics()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.meshtastic.EnvironmentMetrics environment_metrics = 3;</code>
     */
    public function setEnvironmentMetrics($var)
    {
        $this->writeOneof(3, $var);
        return $this;
    }

    /**
     * @return string
     */
    public function getVariant()
    {
        return $this->whichOneof("variant");
    }
}
