<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meshtastic/mesh.proto

namespace Meshtastic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>meshtastic.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string long_name = 2;</code>
     */
    protected $long_name = '';
    /**
     * Generated from protobuf field <code>string short_name = 3;</code>
     */
    protected $short_name = '';
    /**
     * Generated from protobuf field <code>bytes macaddr = 4;</code>
     */
    protected $macaddr = '';
    /**
     * Generated from protobuf field <code>.meshtastic.HardwareModel hw_model = 5;</code>
     */
    protected $hw_model = 0;

    /**
     * Constructor.
     */
    public function __construct($data = NULL) {
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>string long_name = 2;</code>
     */
    public function getLongName()
    {
        return $this->long_name;
    }

    /**
     * Generated from protobuf field <code>string long_name = 2;</code>
     */
    public function setLongName($var)
    {
        GPBUtil::checkString($var, True);
        $this->long_name = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>string short_name = 3;</code>
     */
    public function getShortName()
    {
        return $this->short_name;
    }

    /**
     * Generated from protobuf field <code>string short_name = 3;</code>
     */
    public function setShortName($var)
    {
        GPBUtil::checkString($var, True);
        $this->short_name = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes macaddr = 4;</code>
     */
    public function getMacaddr()
    {
        return $this->macaddr;
    }

    /**
     * Generated from protobuf field <code>bytes macaddr = 4;</code>
     */
    public function setMacaddr($var)
    {
        GPBUtil::checkString($var, False);
        $this->macaddr = $var;
        return $this;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.HardwareModel hw_model = 5;</code>
     */
    public function getHwModel()
    {
        return $this->hw_model;
    }

    /**
     * Generated from protobuf field <code>.meshtastic.HardwareModel hw_model = 5;</code>
     */
    public function setHwModel($var)
    {
        GPBUtil::checkInt32($var);
        $this->hw_model = $var;
        return $this;
    }
}
